project_id = "zkgfymmqvzifrqnczsjs"

[functions.expire-contracts]
verify_jwt = false

[functions.notify-late-payments]
verify_jwt = false

[functions.send-payment-reminder]
verify_jwt = false

[functions.send-receipt-email]
verify_jwt = false

[functions.generate-monthly-receipts]
verify_jwt = false

[functions.send-sms-reminder]
verify_jwt = false

[functions.daily-sms-reminders]
verify_jwt = false

[functions.notify-upcoming-payments]
verify_jwt = false

[functions.check-expiring-contracts]
verify_jwt = false

[functions.fedapay-checkout]
verify_jwt = false

[functions.fedapay-webhook]
verify_jwt = false

[functions.notify-subscription-expiry]
verify_jwt = false
